# Updated : 2025.06.19
# Version : 1.5.7
# GitHub  : https://github.com/Sleeper85/esphome-yambms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

substitutions:
  yambms_version: "1.5.7"

esphome:
  name: ${hostname}
  friendly_name: ${friendly_name}
  # comment: 'Solar system braining and more !'
  # area: 'Technical local'
  project:
    name: Sleeper85.YamBMS
    version: ${yambms_version}
  min_version: 2025.6.0
